name: check-crlf

on: push
jobs:

  build:
    name: check-crlf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: |
            ls
      - name: pwd
        run: |
            pwd
