name: pull_request-path-test

on: 
  pull_request:
    paths:
    - "paths-A/**"
    - "!paths-A/**.md"
  push: 

jobs:

  build:
    name: check-crlf
    runs-on: ubuntu-latest
    steps:
    - run: ls ./*

