name: paths-A-pull_request-path-test

on: 
  pull_request:
    paths:
    - "paths-A/**"
    - "!paths-A/**.md"
  push: 

jobs:

  build:
    name: paths-A-ls
    runs-on: ubuntu-latest
    steps:
    - run: ls paths-A
    - run: ls

