name: paths-B-pull_request-path-test

on: 
  pull_request:
    paths:
    - "paths-B/**"
    - "!paths-B/**.md"
  push: 

jobs:

  build:
    name: paths-B-ls
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls paths-B
    - run: ls
