name: test workflow

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # no test is required
  push:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Prepare the TAG
        id: prepare-the-tag
        run: |
          # strip git ref prefix from version
          TAG=""
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          echo "${{ github.ref }}"
          
          if [ $VERSION = "master" ]; then
            TAG=latest
          fi
          echo "::notice col=5 title=print tag::TAG=$TAG"
          echo "::set-output name=tag::$TAG"